name: Android CI

on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "oracle"
      #     java-version: "17"

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-test

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          avd-name: avd-test
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./test.sh
          ram-size: 2048M
      - name: Save Image as Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: exported-tests
          path: ./logs/
