name: Android CI

on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          script: ./test.sh
      - name: Save Image as Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: exported-tests
          path: ./logs/
