name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
          EITRI_CLI_CLIENT_SECRET: ${{secrets.EITRI_CLI_CLIENT_SECRET}}
          EITRI_CLI_CLIENT_ID: ${{secrets.EITRI_CLI_CLIENT_ID}}
      - run: npm i -g eitri-cli
      - run: node bump-release.js
      - run: eitri push-version
      - run: eitri publish --environment ${{secrets.ENVIRONMENT_ID}} --message "Publish on CI"