name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - main
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  EITRI_CLI_CLIENT_SECRET: ${{secrets.EITRI_CLI_CLIENT_SECRET}}
  EITRI_CLI_CLIENT_ID: ${{secrets.EITRI_CLI_CLIENT_ID}}
  ENVIRONMENT_ID: ${{secrets.ENVIRONMENT_ID}}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"
  #     - run: export EITRI_CLI_CLIENT_SECRET=${{secrets.EITRI_CLI_CLIENT_SECRET}}
  #     - run: export  EITRI_CLI_CLIENT_ID=${{secrets.EITRI_CLI_CLIENT_ID}}
  #     - run: export ENVIRONMENT_ID=${{secrets.ENVIRONMENT_ID}}
  #     - run: npm i -g eitri-cli
  #     - run: node bump-release.js
  #     - run: eitri push-version
  #     - run: eitri publish --environment ${{secrets.ENVIRONMENT_ID}} --message "Publish on CI"
  maestro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0

      - name: Install Android dependencies
        run: |
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;google_apis;x86_64" "emulator"
      - name: Add Android SDK to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/emulator" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Verify emulator installation
        run: |
          which emulator
          emulator -version

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;armeabi-v7a" --device "pixel"

      - name: Launch emulator
        run: |
          nohup emulator -avd test -no-window -no-audio -no-boot-anim -accel on &
          adb wait-for-device
          adb shell input keyevent 82 &

      - name: Wait for emulator to boot
        run: |
          bootanim=""
          until [[ "$bootanim" =~ "stopped" ]]; do
            bootanim=$(adb shell getprop init.svc.bootanim 2>&1)
            sleep 1
          done

      - run: wget https://cdn.83io.com.br/artifacts/eitri-playground.apk
      - run: DEVICE_ID=$(adb devices | grep 'emulator' | awk '{print $1}')
      - run: adb install eitri-playground.apk
      - run: maestro --device $DEVICE_ID test test.yaml --env APP_PATH=eitri-playground.apk
