name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - main
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  EITRI_CLI_CLIENT_SECRET: ${{secrets.EITRI_CLI_CLIENT_SECRET}}
  EITRI_CLI_CLIENT_ID: ${{secrets.EITRI_CLI_CLIENT_ID}}
  ENVIRONMENT_ID: ${{secrets.ENVIRONMENT_ID}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: export EITRI_CLI_CLIENT_SECRET=${{secrets.EITRI_CLI_CLIENT_SECRET}}
      - run: export  EITRI_CLI_CLIENT_ID=${{secrets.EITRI_CLI_CLIENT_ID}}
      - run: export ENVIRONMENT_ID=${{secrets.ENVIRONMENT_ID}}
      - run: npm i -g eitri-cli
      - run: eitri push-version --release
      - run: eitri publish --environment ${{secrets.ENVIRONMENT_ID}} --message "Publish on CI"
